<a href="https://colab.research.google.com/github/xonorKjr/programaci-/blob/main/DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

El Pandas serveix per treballar amb dades, i tenim 3 tipus de estructures.
  - Series: Estructures de una dimensió que porten el seu index asociat a les segones.
  -  Data Frames: Estructures e dues dimensions
  - Panells: Estructures de tres dimensions

In [ ]:
!pip install pandas
!apt-get install phython3.12

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package phython3.12
E: Couldn't find any package by glob 'phython3.12'
E: Couldn't find any package by regex 'phython3.12'

In [ ]:
!apt-get install python3.12

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libpython3.12-minimal libpython3.12-stdlib mailcap mime-support python3.12-minimal
Suggested packages:
  python3.12-venv binfmt-support
The following NEW packages will be installed:
  libpython3.12-minimal libpython3.12-stdlib mailcap mime-support python3.12 python3.12-minimal
0 upgraded, 6 newly installed, 0 to remove and 49 not upgraded.
Need to get 5,548 kB of archives.
After this operation, 22.8 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 mailcap all 3.70+nmu1ubuntu1 [23.8 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 mime-support all 3.66 [3,696 B]
Get:3 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 libpython3.12-minimal amd64 3.12.7-1+jammy1 [880 kB]
Get:4 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 python3.12-minimal amd64 3.12.7-1+jammy1 [2,497 kB]
Get:5 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 libpython3.12-stdlib amd64 3.12.7-1+jammy1 [2,049 kB]
Get:6 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 python3.12 amd64 3.12.7-1+jammy1 [94.7 kB]
Fetched 5,548 kB in 16s (340 kB/s)
Selecting previously unselected package libpython3.12-minimal:amd64.
(Reading database ... 123630 files and directories currently installed.)
Preparing to unpack .../0-libpython3.12-minimal_3.12.7-1+jammy1_amd64.deb ...
Unpacking libpython3.12-minimal:amd64 (3.12.7-1+jammy1) ...
Selecting previously unselected package python3.12-minimal.
Preparing to unpack .../1-python3.12-minimal_3.12.7-1+jammy1_amd64.deb ...
Unpacking python3.12-minimal (3.12.7-1+jammy1) ...
Selecting previously unselected package mailcap.
Preparing to unpack .../2-mailcap_3.70+nmu1ubuntu1_all.deb ...
Unpacking mailcap (3.70+nmu1ubuntu1) ...
Selecting previously unselected package mime-support.
Preparing to unpack .../3-mime-support_3.66_all.deb ...
Unpacking mime-support (3.66) ...
Selecting previously unselected package libpython3.12-stdlib:amd64.
Preparing to unpack .../4-libpython3.12-stdlib_3.12.7-1+jammy1_amd64.deb ...
Unpacking libpython3.12-stdlib:amd64 (3.12.7-1+jammy1) ...
Selecting previously unselected package python3.12.
Preparing to unpack .../5-python3.12_3.12.7-1+jammy1_amd64.deb ...
Unpacking python3.12 (3.12.7-1+jammy1) ...
Setting up libpython3.12-minimal:amd64 (3.12.7-1+jammy1) ...
Setting up mailcap (3.70+nmu1ubuntu1) ...
Setting up python3.12-minimal (3.12.7-1+jammy1) ...
Setting up mime-support (3.66) ...
Setting up libpython3.12-stdlib:amd64 (3.12.7-1+jammy1) ...
Setting up python3.12 (3.12.7-1+jammy1) ...
Processing triggers for man-db (2.10.2-1) ...

In [ ]:
import pandas as pd
setmana= pd.Series(["Dilluns","Dimarts","Dimecres","Dijous","Divendres","Dissabte","Diumenge"])

print(setmana)

0      Dilluns
1      Dimarts
2     Dimecres
3       Dijous
4    Divendres
5     Dissabte
6     Diumenge
dtype: object

Serie numerica:  12,58,63,47,81,35

Mira la llargada (size)

Suma tots els valors num. (sum) cal que la suma digui "L'import total es (sum)"

In [ ]:
import pandas as pd
num = pd.Series([12,58,63,47,81,35])
num.size

6

In [ ]:
import pandas as pd
num = pd.Series([12,58,63,47,81,35])
suma=num.sum()
print(f"L'import total és {suma}")

L'import total és 296

In [ ]:
import pandas as pd
num = pd.Series([12,58,63,47,81,35])
num.mean()
round(num.mean(),2)

49.33

In [ ]:
import pandas as pd
num = pd.Series([12,58,63,47,81,35])
maxim=num.max()
minim=num.min()
print(maxim)
print(minim)

In [ ]:
import pandas as pd
num = pd.Series([12,58,63,47,81,35])
num.cumsum()

0     12
1     70
2    133
3    180
4    261
5    296
dtype: int64

In [ ]:
import pandas as pd
num = pd.Series([12,58,63,47,81,35])
num.value_counts()

12    1
58    1
63    1
47    1
81    1
35    1
Name: count, dtype: int64

In [ ]:
import pandas as pd
num = pd.Series([12,8,5,5,14,3,12,7])
variables=num.size
print(variables)
suma=num.sum()
print(f"L'import total és {suma}")
mitjana=num.mean()
print(mitjana)
arrodonit=round(num.mean(),2)
print(arrodonit)
maxim=num.max()
minim=num.min()
print(maxim)
print(minim)
cum=num.cumsum()
print(cum)
num.value_counts()

8
L'import total és 66
8.25
8.25
14
3
0    12
1    20
2    25
3    30
4    44
5    47
6    59
7    66
dtype: int64

12    2
5     2
8     1
14    1
3     1
7     1
Name: count, dtype: int64

In [ ]:
import pandas as pd
gent = pd.DataFrame([{"Nombre":"Pedro","Edad":25,"Altura":1.68},
                     {"Nombre":"Sonia","Edad":52,"Altura":1.74},
                     {"Nombre":"Lluis","Edad":19,"Altura":1.81},
                     {"Nombre":"Marta","Edad":33,"Altura":1.59},
                     {"Nombre":"Julian","Edad":48,"Altura":1.71},
                     {"Nombre":"Nerea","Edad":61,"Altura":1.78},
])
gent

   Nombre  Edad  Altura
0   Pedro    25    1.68
1   Sonia    52    1.74
2   Lluis    19    1.81
3   Marta    33    1.59
4  Julian    48    1.71
5   Nerea    61    1.78

Persona altura mínima

In [ ]:
import pandas as pd
gent = pd.DataFrame([{"Nombre":"Pedro","Edad":25,"Altura":1.68},
                     {"Nombre":"Sonia","Edad":52,"Altura":1.74},
                     {"Nombre":"Lluis","Edad":19,"Altura":1.81},
                     {"Nombre":"Marta","Edad":33,"Altura":1.59},
                     {"Nombre":"Julian","Edad":48,"Altura":1.71},
                     {"Nombre":"Nerea","Edad":61,"Altura":1.78},
])
persona_min = gent.loc[gent["Altura"].idxmin()]
print(persona_min)

Nombre    Marta
Edad         33
Altura     1.59
Name: 3, dtype: object

Persona altura màxima

In [ ]:
import pandas as pd
gent = pd.DataFrame([{"Nombre":"Pedro","Edad":25,"Altura":1.68},
                     {"Nombre":"Sonia","Edad":52,"Altura":1.74},
                     {"Nombre":"Lluis","Edad":19,"Altura":1.81},
                     {"Nombre":"Marta","Edad":33,"Altura":1.59},
                     {"Nombre":"Julian","Edad":48,"Altura":1.71},
                     {"Nombre":"Nerea","Edad":61,"Altura":1.78},
])
persona_min = gent.loc[gent["Altura"].idxmax()]
print(persona_min)

Nombre    Lluis
Edad         19
Altura     1.81
Name: 2, dtype: object

Promig edats i arrodonir a 2 decimals

In [1]:
import pandas as pd
gent = pd.DataFrame([{"Nombre":"Pedro","Edad":25,"Altura":1.68},
                     {"Nombre":"Sonia","Edad":52,"Altura":1.74},
                     {"Nombre":"Lluis","Edad":19,"Altura":1.81},
                     {"Nombre":"Marta","Edad":33,"Altura":1.59},
                     {"Nombre":"Julian","Edad":48,"Altura":1.71},
                     {"Nombre":"Nerea","Edad":61,"Altura":1.78},
])
edad_promig = gent["Edad"].mean().round(2)
print(edad_promig)

39.67

Afegir columna al DataFrame que sigui "Institut"---->MVM

In [ ]:
import pandas as pd
gent = pd.DataFrame([{"Nombre":"Pedro","Edad":25,"Altura":1.68,"Institut":"MVM"},
                     {"Nombre":"Sonia","Edad":52,"Altura":1.74,"Institut":"MVM"},
                     {"Nombre":"Lluis","Edad":19,"Altura":1.81,"Institut":"MVM"},
                     {"Nombre":"Marta","Edad":33,"Altura":1.59,"Institut":"MVM"},
                     {"Nombre":"Julian","Edad":48,"Altura":1.71,"Institut":"MVM"},
                     {"Nombre":"Nerea","Edad":61,"Altura":1.78,"Institut":"MVM"},

])
gent

   Nombre  Edad  Altura Institut
0   Pedro    25    1.68      MVM
1   Sonia    52    1.74      MVM
2   Lluis    19    1.81      MVM
3   Marta    33    1.59      MVM
4  Julian    48    1.71      MVM
5   Nerea    61    1.78      MVM

Afegir coolumna al DataFrame que sigui edat 2= edat+2

In [ ]:
import pandas as pd
gent = pd.DataFrame([{"Nombre":"Pedro","Edad":25,"Altura":1.68,"Institut":"MVM"},
                     {"Nombre":"Sonia","Edad":52,"Altura":1.74,"Institut":"MVM"},
                     {"Nombre":"Lluis","Edad":19,"Altura":1.81,"Institut":"MVM"},
                     {"Nombre":"Marta","Edad":33,"Altura":1.59,"Institut":"MVM"},
                     {"Nombre":"Julian","Edad":48,"Altura":1.71,"Institut":"MVM"},
                     {"Nombre":"Nerea","Edad":61,"Altura":1.78,"Institut":"MVM"},

])
gent['Edad+2'] = gent['Edad'] + 2
gent

   Nombre  Edad  Altura Institut  Edad+2
0   Pedro    25    1.68      MVM      27
1   Sonia    52    1.74      MVM      54
2   Lluis    19    1.81      MVM      21
3   Marta    33    1.59      MVM      35
4  Julian    48    1.71      MVM      50
5   Nerea    61    1.78      MVM      63